config/routes.rb
Prismbox::Application.routes.draw do
  get "numbeers/fibonacci"
  resources :laptops
  resources :users

  controller :users do
    get "order_history", to: :order_history
  end

  controller :numbeers do
    get "fibonacci", to: :fibonacci
  end

  resources :orders

  controller :orders do
    get "confirm_all", to: :confirm_all_new_orders
    patch "confirm_all", to: :confirm_all_new_orders
  end

  controller :sessions do
    get 'login', to: :new
    post 'login', to: :create 
    delete 'logout', to: :destroy
  end

  get "admin", to: 'admin#dashboard'

  get "catalog/index"
  root "catalog#welcome", as: "welcome"

  

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, :last_name, :email, :department, presence: true
  validates :email, uniqueness: true
  has_secure_password
  before_destroy :ensure_an_admin_remains
  has_many :orders

  def admin
    self.email == admin_email
  end

  private

  def ensure_an_admin_remains
    raise "Can’t delete admin" if admin
  end

  def admin_email
    "testadmin@example.com"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, except:[:index]
  before_action :admin_authorize, only:[:index]
  before_action :get_user, only:[:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_parameter)
    @user.attributes = {current_borrowed_laptop: "Not Yet", current_borrowed_date: "N/A"}
    if @user.save
      session[:user_id] = @user.email
      redirect_to @user, notice: notice_message("#{@user.first_name} #{@user.last_name}", "created")
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_parameter)
      redirect_to @user, notice: notice_message("#{@user.first_name} #{@user.last_name}", "updated")
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  def order_history
    @orders_type = params[:type]
    @orders = orders_by(@orders_type)
  end

  private

  def get_user
    @user = User.find(params[:id])
  end

  def user_parameter
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :department, :current_borrowed_laptop, :current_borrowed_date)
  end

  def notice_message (user_name, action)
    "#{user_name} was successfully #{action}."
  end

  def orders_by type
    if type == "all"
      Order.where(user_id: current_user.id).order("updated_at DESC")
    else
      Order.where(user_id: current_user.id, order_status: "PROCESSING").order("updated_at DESC")
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class = "alert alert-danger">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> 
        prohibited this laptop from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li> <% end %>
      </ul>
    </div> 
  <% end %>
  <div class="info-detail">
    <label>FULL NAME</label>
    <%= f.text_field :first_name, class: "info-input sm", placeholder: "FIRST NAME" %>
     <%= f.text_field :last_name, class: "info-input sm", placeholder: "LAST NAME" %><br>
    <label>EMAIL</label>
    <%= f.email_field :email, class: "info-input", placeholder:"EMAIL" %>
    <label>PASSWORD</label>
    <%= f.password_field :password, class: "info-input", placeholder:"PASSWORD" %>
    <label>PASSWORD CONFIRMATION</label>
    <%= f.password_field :password_confirmation, class: "info-input", placeholder:"PASSWORD" %>
    <label>DEPARTMENT</label>
    <label class="radio-inline">Software<%= f.radio_button :department, 'Software', checked: true %></label>
    <label class="radio-inline">UX </b><%= f.radio_button :department, 'UX' %></label>
  </div>
  <%= f.submit "Make Account", class: "btn btn-success info-save" %><br><br>
<% end %>

app/views/users/edit.html.erb
<div class="contents">
  <h1>Change Account Settings</h1>
  <%= render "form" %>
  <% if current_user.admin %>
    <%= link_to "Back to Users List", users_url , class: "buttons btn btn-primary"%>
  <% else %>
    <%= link_to "Home", "/" , class: "buttons btn btn-primary"%>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="contents">
  <h1>USERS LIST</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>FULL NAME</th>
        <th>EMAIL</th>
        <th>DEPARTMENT</th>
        <th>CURRENT BORROWED LAPTOP</th>
        <th>CURRENT BORROWED DATE</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td></td>
        <td><%= user.first_name %> <%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.department %></td>
        <td><%= user.current_borrowed_laptop %></td>
        <td><%= user.current_borrowed_date %></td>
        <td><%= link_to "SHOW", user_path(user) %></td>
        <td><%= link_to "EDIT", edit_user_path(user) %></td>
        <td><%= link_to "DELETE", user, method: :delete, data: {confirm: "Are you sure? You can’t cancel this action."}%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Home", admin_url , class: "btn btn-primary"%>
</div>

app/views/users/new.html.erb
<div class="contents">
  <h1>Registration<br><small>New to PrismBox? Register Below.</small></h1>
  <%= render "form" %>
  <%= link_to "Back", '/' , class: "buttons btn btn-primary"%>
</div>

app/views/users/order_history.html.erb
<div class="container">
  <div class="starter-template">
    <h1><%= "#{current_user.first_name.upcase} #{@orders_type.capitalize}" %> Orders</h1>
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th>LAPTOP MODEL</th>
          <th>LAPTOP SERIAL NUMBER</th>
          <th>BORROWED DATE</th>
          <th>STATUS</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td></td>
          <td><%= Laptop.find(order.laptop_id).model_ %></td>
          <td><%= order.laptop_serial_number %></td>
          <td><%= order.updated_at.to_date %></td>
          <td><%= order.order_status %></td>
          <td>
          <% if order.order_status == "PROCESSING"  %>
            <%=link_to "CANCEL", order, method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= link_to "Home", "/" , class: "btn btn-primary"%>
</div>

app/views/users/show.html.erb
<div class="contents">
  <% if notice %>
      <p class = "alert alert-success"><%= notice %></p> 
  <% end %>
  <h1 class="info-title"><span><%= @user.first_name.titlecase %> <%= @user.last_name.titlecase %></span> PROFILE</h1>
  <div class="info-detail">
    <label>FULL NAME</label>
    <div class="info"><%= @user.first_name.titlecase %> <%= @user.last_name.titlecase %></div>
    <label>EMAIL</label>
    <div class="info"><%= @user.email %></div>
    <label>DEPARTMENT</label>
    <div class="info"><%= @user.department %></div>
    <label>CURRENT RENTED LAPTOP</label>
    <div class="info"><%= @user.current_borrowed_laptop %></div>
    <label>CURRENT RENTED DATE</label>
    <div class="info"><%= @user.current_borrowed_date %></div>
  </div><br>
  <div class="buttons">
    <%= link_to "Edit", edit_user_path(@user), class: "btn btn-info" %> 
    <%= link_to "Delete", @user, method: :delete, data: {confirm: "Are you sure? You can’t cancel this action."}, class: "btn btn-danger" %></td><br><br>
    <% if current_user.admin %>
      <%= link_to "Back to Users List", users_url , class: "btn btn-primary"%>
    <% else %>
      <%= link_to "Home", "/" , class: "btn btn-primary"%>
    <% end %>
  </div><br>
</div>