config/routes.rb
Prismbox::Application.routes.draw do
  get "numbeers/fibonacci"
  resources :laptops
  resources :users

  controller :users do
    get "order_history", to: :order_history
  end

  controller :numbeers do
    get "fibonacci", to: :fibonacci
  end

  resources :orders

  controller :orders do
    get "confirm_all", to: :confirm_all_new_orders
    patch "confirm_all", to: :confirm_all_new_orders
  end

  controller :sessions do
    get 'login', to: :new
    post 'login', to: :create 
    delete 'logout', to: :destroy
  end

  get "admin", to: 'admin#dashboard'

  get "catalog/index"
  root "catalog#welcome", as: "welcome"

  

end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :full_name, :email, :laptop_serial_number, presence: true
  belongs_to :user
  belongs_to :laptop
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :admin_authorize, except:[:show, :new, :create, :destroy]
  before_action :get_order, only:[:show, :edit, :update, :destroy]
  before_action :get_session_laptop_id, only:[:edit, :update, :destroy]
  before_action :check_available_rental, :check_available_laptop_state, only:[:create]

  def index
   if params[:state] == "all" || params[:state].nil?
      @orders = Order.all
    else
      @orders = index_by(params[:state].upcase)
    end
  end

  def show
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.create(order_parameter)
    @order.attributes = {laptop_id: session[:laptop_id].id, user_id: current_user.id, order_status: "PROCESSING"}
    if @order.save
      change_laptop_status("RESERVED")
      change_user_rent_status(current_user, "REQUEST", "REQUEST")
      redirect_to @order, notice: 'Successfully ordered.'
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @order.update_attributes(order_parameter)
      change_others_status(@order.order_status, @order)
      redirect_to @order, notice: 'Order status was successfully updated.'
    else
      render "edit"
    end
  end

  def confirm_all_new_orders
    orders = Order.where(order_status: "PROCESSING")
    orders.each do |order|
      session[:laptop_id] = Laptop.find(order.laptop_id)
      order.update_attributes(order_status: "CONFIRMED")
      change_others_status(order.order_status, order)
    end
    redirect_to admin_url, notice: 'All new orders status was successfully confirmed.'
  end

  def destroy
    unless current_user.admin
      if @order.order_status == "CONFIRMED"
        redirect_to "/", notice: "You can't cancel a order confirmed."
      else
        cancel_order("/")
      end
    else
      cancel_order(orders_url)
    end
  end

  def cancel_order url
    @order.destroy
    change_laptop_status("STOCKS")
    change_user_rent_status(User.find(@order.user_id), "Not Yet", "N/A")
    redirect_to url, notice: "Order was successfully canceled"
  end

  private
  def index_by state
    Order.where(order_status: state)
  end

  def get_session_laptop_id
    session[:laptop_id] = Laptop.find(@order.laptop_id)
  end

  def get_order
    @order = Order.find(params[:id])
  end

  def order_parameter
    params.require(:order).permit(:full_name, :email, :laptop_serial_number, :order_status)
  end

  def check_available_rental
    unless current_user.current_borrowed_laptop == "Not Yet"
      redirect_to "/", notice: "You can't borrow before returning a laptop borrowed"
    end
  end

  def check_available_laptop_state
    unless session[:laptop_id].state == "STOCKS"
      redirect_to({controller:'catalog', action:'index'}, notice: "Chosen laptop is already #{session[:laptop_id].state.downcase}")
    end    
  end

  def change_laptop_status statement
    session[:laptop_id].update_attributes(state: statement)
    session[:laptop_id] = nil
  end

  def change_user_rent_status user, laptop, date
    user.update_attributes(current_borrowed_laptop: laptop, current_borrowed_date: date)
  end

  def change_others_status statement, order
    if statement == "CONFIRMED"
      change_laptop_status("RENTED")
      change_user_rent_status(User.find(order.laptop_id), order.laptop_serial_number, order.updated_at.to_date)
    elsif statement == "RETURNED"
      change_laptop_status("STOCKS")
      change_user_rent_status(User.find(order.laptop_id), "Not Yet", "N/A")      
    else
      change_laptop_status("RESERVED")
      change_user_rent_status(User.find(order.laptop_id), "REQUEST", "REQUEST")
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def full_name_of user
    "#{user.first_name.titlecase} #{user.last_name.titlecase}"
  end

  def consumer_user order
    if order.id.nil?
      current_user
    else
      User.find(order.user_id)
    end
  end
end

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
  <% if @order.errors.any? %>
    <div class = "alert alert-danger">
      <h2>
        <%= pluralize(@order.errors.count, "error") %>
        prohibited this order from being saved:
      </h2>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li> <% end %>
      </ul>
    </div> 
  <% end %>
  <div class="info-detail">
    <label>FULL NAME</label>
    <%= f.text_field :full_name, value: full_name_of(consumer_user(@order)), class: "info-input", readonly: true %>
    <label>EMAIL</label>
    <%= f.text_field :email, value: consumer_user(@order).email, class: "info-input", readonly: true %>
    <label>LAPTOP SERIAL NUMBER</label>
    <%= f.text_field :laptop_serial_number, value: session[:laptop_id].serial_number, class: "info-input", readonly: true %>
    <% if current_user.admin %>
      <label>ORDER STATEMENT</label>
      <label class="radio-inline">
        <%= f.radio_button :order_status, "CONFIRMED"%> Confirm
      </label>
      <label class="radio-inline">
        <%= f.radio_button :order_status, "PROCESSING"%> Processing
      </label>
      <label class="radio-inline">
        <%= f.radio_button :order_status, "RETURNED"%> Return
      </label>
    <% end %>
  </div><br>
  <%= f.submit "Place your order", class: "btn btn-success info-save" %><br><br>
<% end %>

app/views/orders/edit.html.erb
<div class="contents">
  <h1>Edit Order</h1>
  <%= render "form" %>
  <%= link_to "Back to List", orders_url , class: "btn btn-primary"%>
</div>

app/views/orders/index.html.erb
<div class="contents">
  <h1>Order LIST</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>FULL NAME</th>
        <th>EMAIL</th>
        <th>LAPTOP SERIAL NUMBER</th>
        <th>ORDER CREATE DATE</th>
        <th>ORDER STATEMENT</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td></td>
        <td><%= order.full_name %></td>
        <td><%= order.email %></td>
        <td><%= order.laptop_serial_number %></td>
        <td><%= order.created_at.to_date %></td>
        <td><%= order.order_status %></td>
        <td><%= link_to "SHOW", order_path(order) %></td>
        <td><%= link_to "EDIT", edit_order_path(order) %></td>
        <td><%= link_to "DELETE", order, method: :delete, data: {confirm: "Are you sure? You can’t cancel this action."}%></td>
      </tr>
      <% end %>
    </tbody>
  </table><br>
  <% if params[:state] == "processing" %>
    <%= link_to "Confirm All", confirm_all_url, data: {confirm: "Do you want to confirm all new orders?"}, class: "btn btn-info" %><br><br>
  <% end %>
  <%= link_to "Home", admin_url , class: "btn btn-primary"%>
</div>

app/views/orders/new.html.erb
<div class="contents">
  <h1>Review Your Order</h1>
  <%= render "form" %>
  <%= link_to "Back to List", laptops_url , class: "btn btn-primary"%>
</div>

app/views/orders/show.html.erb
<div class="contents">
  <% if notice %>
      <p class = "alert alert-success"><%= notice %></p> 
  <% end %>
  <h1 class="info-title">Order Detail</h1>
  <div class="info-detail">
    <label>FULL NAME</label>
    <div class="info"><%= @order.full_name %></div>
    <label>EMAIL</label>
    <div class="info"><%= @order.email %></div>
    <label>RENT LAPTOP SERIAL NUMBER</label>
    <div class="info"><%= @order.laptop_serial_number %></div>
    <% if current_user.admin %>
      <label>ORDER STATEMENT</label>
      <div class="info"><%= @order.order_status %></div>
    <% end %>
  </div><br>
  <div class="buttons">
    <% if current_user.admin %>
      <%= link_to "Edit", edit_order_path(@order), class: "btn btn-info" %>
      <%= link_to "Delete", @order, method: :delete, data: {confirm: "Are you sure? You can’t cancel this action."}, class: "btn btn-danger" %></td><br><br>
      <%= link_to "Back to List", orders_url , class: "btn btn-primary"%>
      <% else %>
        <%= link_to "Home", "/" , class: "btn btn-primary"%>
    <% end %>
  </div><br>
</div>