config/routes.rb
Prismbox::Application.routes.draw do
  get "numbeers/fibonacci"
  resources :laptops
  resources :users

  controller :users do
    get "order_history", to: :order_history
  end

  controller :numbeers do
    get "fibonacci", to: :fibonacci
  end

  resources :orders

  controller :orders do
    get "confirm_all", to: :confirm_all_new_orders
    patch "confirm_all", to: :confirm_all_new_orders
  end

  controller :sessions do
    get 'login', to: :new
    post 'login', to: :create 
    delete 'logout', to: :destroy
  end

  get "admin", to: 'admin#dashboard'

  get "catalog/index"
  root "catalog#welcome", as: "welcome"

  

end

app/models/laptop.rb
class Laptop < ActiveRecord::Base
  validates :serial_number, :model_, :hdd_size, :cpu_speed, :ram, :screen_size, :purchased_date, presence: true
  validate :purchased_date_in_the_future
  has_many :orders

  private
  def purchased_date_in_the_future
    if purchased_date > Date.today
      errors.add(:purchased_date, "can't be in the future")
    end
  end
end

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  # before_action :admin_authorize, except:[:index, :show]
  # before_action :get_laptop, only:[:show, :edit, :update, :destroy]

  def index
    if params[:state] == "all" || params[:state].nil?
      @laptops = Laptop.all
    else
      @laptops = index_by(params[:state].upcase)
    end
  end

  def show
    session[:laptop_id] = @laptop
  end

  def new
    @laptop = Laptop.new
  end

  def create
    @laptop = Laptop.create(laptop_parameter)
    if @laptop.save
      @laptop.update_attributes(state: "STOCKS")
      redirect_to @laptop, notice: 'Laptop was successfully created.'
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @laptop.update_attributes(laptop_parameter)
      redirect_to @laptop, notice: 'Laptop was successfully updated.'
    else
      render "edit"
    end
  end

  def destroy
    @laptop.destroy
    redirect_to laptops_url
  end

  private
  def get_laptop
    @laptop = Laptop.find(params[:id])
  end

  def laptop_parameter
    params.require(:laptop).permit(:serial_number, :model_, :hdd_size, :cpu_speed, :ram, :screen_size, :purchased_date, :state)
  end

  def index_by state
    Laptop.where(state: state)
  end
end

app/helpers/laptops_helper.rb
module LaptopsHelper
end

app/views/laptops/_form.html.erb
<%= form_for @laptop do |f| %>
  <% if @laptop.errors.any? %>
    <div class = "alert alert-danger">
      <h2>
        <%= pluralize(@laptop.errors.count, "error") %>
        prohibited this laptop from being saved:
      </h2>
      <ul>
        <% @laptop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li> <% end %>
      </ul>
    </div> 
  <% end %>
  <div class="info-detail">
    <label>SERIAL NUMBER</label>
    <%= f.text_field :serial_number, class: "info-input", placeholder: "SERIAL NUMBER" %>
    <label>MODEL</label>
    <%= f.text_field :model_, class: "info-input", placeholder:"MODEL" %>
    <label>HDD SIZE</label>
    <%= f.text_field :hdd_size, class: "info-input", placeholder:"HDD SIZE" %>
    <label>CPU SPEED</label>
    <%= f.text_field :cpu_speed, class: "info-input", placeholder:"CPU SPEED" %>
    <label>RAM</label>
    <%= f.text_field :ram, class: "info-input", placeholder:"RAM" %>
    <label>SCREEN SIZE</label>
    <%= f.text_field :screen_size, class: "info-input", placeholder:"RAM" %>
    <label>PURCHASED DATE</label>
    <%= f.date_field :purchased_date, class: "info-input" %>
  </div><br>
  <%= f.submit "Save Laptop", class: "btn btn-success info-save" %><br><br>
<% end %>

app/views/laptops/edit.html.erb
<div class="contents">
  <h1>Edit Laptop</h1>
  <%= render "form" %>
  <%= link_to "Back to List", laptops_url , class: "buttons btn btn-primary"%>
</div>

app/views/laptops/index.html.erb
<div class="contents">
  <h1>LAPTOPS LIST</h1>
  <table class="table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>SERIAL NUMBER</th>
        <th>MODEL</th>
        <th>HDD SIZE</th>
        <th>CPU SPEED</th>
        <th>RAM</th>
        <th>SCREEN SIZE</th>
        <th>PURCHASED DATE</th>
        <th>CURRENT STATE</th>
        <th></th>
        <% if current_user.admin %>
          <th></th>
          <th></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @laptops.each do |laptop| %>
      <tr>
        <td></td>
        <td><%= laptop.serial_number %></td>
        <td><%= laptop.model_ %></td>
        <td><%= laptop.hdd_size %></td>
        <td><%= laptop.cpu_speed %></td>
        <td><%= laptop.ram %></td>
        <td><%= laptop.screen_size %></td>
        <td><%= laptop.purchased_date %></td>
        <td><%= laptop.state %></td>
        <td><%= link_to "SHOW", laptop_path(laptop) %></td>
        <% if current_user.admin %>
          <td><%= link_to "EDIT", edit_laptop_path(laptop) %></td>
          <td><%= link_to "DELETE", laptop, method: :delete, data: {confirm: "Are you sure? You can’t cancel this action."}%></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% if current_user.admin %>
    <%= link_to "New Laptop", new_laptop_path , class: "btn btn-primary"%><br><br>
    <%= link_to "Home", admin_url , class: "btn btn-primary"%>
  <% end %>
</div>

app/views/laptops/new.html.erb
<div class="contents">
  <h1>New Laptop</h1>
  <%= render "form" %>
  <%= link_to "Back to List", laptops_url , class: "buttons btn btn-primary"%>
</div>

app/views/laptops/show.html.erb
<div class="contents">
  <% if notice %>
      <p class = "alert alert-success"><%= notice %></p>
  <% end %>
  <h1 class="info-title">LAPTOP / <%= @laptop.serial_number%></h1>
  <div class="info-detail">
    <label>SERIAL NUMBER</label>
    <div class="info"><%= @laptop.serial_number %></div>
    <label>MODEL</label>
    <div class="info"><%= @laptop.model_ %></div>
    <label>HDD SIZE</label>
    <div class="info"><%= @laptop.hdd_size %></div>
    <label>CPU SPEED</label>
    <div class="info"><%= @laptop.cpu_speed %></div><br>
    <label>RAM</label>
    <div class="info"><%= @laptop.ram %></div><br>
    <label>SCREEN SIZE</label>
    <div class="info"><%= @laptop.screen_size %></div><br>
    <label>PURCHASED DATE</label>
    <div class="info"><%= @laptop.purchased_date %></div><br>
    <label>CURRENT STATE</label>
    <div class="info"><%= @laptop.state %></div>
  </div><br>
  <div class="buttons">
    <% if current_user.admin %>
      <%= link_to "Edit", edit_laptop_path(@laptop), class: "btn btn-info" %>
      <%= link_to "Delete", @laptop, method: :delete, data: {confirm: "Are you sure? You can’t cancel this action."}, class: "btn btn-danger" %></td><br><br>
    <% end %>
    <%= link_to "Proceed to borrow", new_order_path, class: "btn btn-info" %>
    <%= link_to "Back to List", laptops_url , class: "btn btn-primary"%>
  </div>
</div>