config/routes.rb
Prismbox::Application.routes.draw do
  get "numbeers/fibonacci"
  resources :laptops
  resources :users

  controller :users do
    get "order_history", to: :order_history
  end

  controller :numbeers do
    get "fibonacci", to: :fibonacci
  end

  resources :orders

  controller :orders do
    get "confirm_all", to: :confirm_all_new_orders
    patch "confirm_all", to: :confirm_all_new_orders
  end

  controller :sessions do
    get 'login', to: :new
    post 'login', to: :create 
    delete 'logout', to: :destroy
  end

  get "admin", to: 'admin#dashboard'

  get "catalog/index"
  root "catalog#welcome", as: "welcome"

  

end

app/views/layouts/_account.html.erb
<div class="nav-your-account">
  <%= link_to title_url_by_user, class: "nav-signin-title" do %>
    <p>HELLO, <%= current_user.first_name.upcase %><br>Your Account <b class="caret"></b></p>
  <% end %>
  <ul class="nav-account-dropdown-menu">
    <li class="nav-account-dropdown-header">Settings</li>
    <li><%= link_to "Change Account Setting", edit_user_path(current_user), class: "nav-account-dropdown-link" %></li>
    <li><%= link_to "Cancel Account", current_user, method: :delete, data: {confirm: "Are you sure? You can’t cancel this action."}, class: "nav-account-dropdown-link" %></li>
    <li class="nav-account-dropdown-divider"></li>
    <li class="nav-account-dropdown-header">Your Orders</li>
    <li><%= link_to "Open Order", {action: "order_history", controller: "users", type: "open"}, class: "nav-account-dropdown-link" %></li>
    <li><%= link_to "Order History", {action: "order_history", controller: "users", type: "all"}, class: "nav-account-dropdown-link" %></li>
    <li class="nav-account-dropdown-divider"></li>
    <li><%= link_to "Log Out", logout_url, method: :delete , class: "nav-account-dropdown-logout" %></li>
  </ul>
</div>

app/views/layouts/_header.html.erb
<div class="navbar" role="navigation">
  <div class="nav-logo">
    <%= link_to "PrismBox", title_url_by_user , class: "nav-logo-link"%>
  </div>
  <%= render "layouts/login" %>
  <%= render "layouts/logout" %>
</div>

app/views/layouts/_login.html.erb
<% if session[:user_id].nil? %>
  <%= form_tag login_url, class: "nav-account-login" do %>
    <%= text_field_tag :email, params[:email], placeholder: "EMAIL", class: "nav-account-id" %>
    <%= password_field_tag :password, params[:password], placeholder: "PASSWORD", class: "nav-account-pw" %>
    <%= submit_tag "Login", class: "header_btn login" %>
  <% end %>
  <h5 class="nav-new-account">New to PrismBox? <%= link_to "Start Here", new_user_path %> </h5>
<% end %>

app/views/layouts/_logout.html.erb
<% unless session[:user_id].nil? %>
  <%= render "layouts/account" %>
  <div class="logout">
    <%= link_to "Logout", logout_url, method: :delete , class: "header_btn logout" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prismbox</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= image_tag "home.jpg", class: "home-image"%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>